Require python-bugzilla
Otherwise you'll get:

    $ PYTHONPATH=. python -m portingdb serve
    Traceback (most recent call last):
      File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File ".../portingdb/portingdb/__main__.py", line 1, in <module>
        from portingdb.cli import main
      File ".../portingdb/portingdb/cli.py", line 11, in <module>
        from portingdb.check_fti import check_fti
      File ".../portingdb/portingdb/check_fti.py", line 11, in <module>
        import bugzilla
    ModuleNotFoundError: No module named 'bugzilla'